#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# Привязка рабочих столов к монитору(ам)
# bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc monitor DP1 -d 1 2 3 4 5 6
bspc monitor DP2 -d 7 8 9 0

# Рамки и отступы
bspc config border_width         1
bspc config window_gap           0

# Цвет рамки
bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#344756"

# Цвет пространства при выборе положения нового окна
bspc config presel_feedback_color "#595B82"

# Фокус окна наведение курсора
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

# Коэффициент разделение. Сколько процентов останется от родительского окна при открытии нового
bspc config split_ratio          0.5

# Отступы и рамки, когда открыто одно окно
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Правила приложений
bspc rule -a firefox desktop=^4

$HOME/.config/bspwm/display.sh
$HOME/.config/polybar/launch.sh
feh --no-fehbg --bg-scale $HOME/como_lake.jpeg

